name: 01 - Integration & Quality

on:
  workflow_call: # Permet d'être appelé par un workflow parent
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: microcrm
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports: [5432:5432]
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java, javascript
      - name: Setup Env
        uses: actions/setup-java@v4
        with: { java-version: '17', distribution: 'temurin' }
      - name: Run Backend Tests
        run: cd back && ./gradlew test
        env:
          DB_HOST: localhost
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3